### ISSUE TITLE
Import Broken

### ISSUE THREAD

**Issue by a3ilson** [0sm0s1z/Voltaire#28]
I attempted to test this out but appears to be broken.

1. Uploaded CSV index == didn't work
2. Created simple two line CSV, to test == didn't work
3. Download the [testdata.csv](https://raw.githubusercontent.com/0sm0s1z/Voltaire/master/testdata.csv) == didn't work

Please provide an updated demo/example CSV and/or instructions that work.

**Comment by naivros** [comment]
Thank you for the issue report. 

The application is throwing an error in development, which is hidden in production. It appears that the file /src/containers/Home.js lines 247-248 are referencing an incorrect item in the array. To remediate this issue, I have created a PR, #29 


` #ret.path.o[] => ret.path.pieces_[]`.

This is most likely due to the recent update in dependencies, and should be merged in the near future. 

However, if you need this feature immediately, I would recommend copying the rows directly from Excel to Voltaire. 
  **1)** Highlight Table in Excel 
  **2)** Create blank cells in Voltaire (however many rows you are importing from Excel)
  **3)** Paste the highlighted cells in the top left-most cell, and it will fill the remaining cells from the selection. 

![Snag_574311c](https://user-images.githubusercontent.com/28509720/114449361-a75f9b00-9ba2-11eb-90c4-9e27fb44dd8b.png)

![image](https://user-images.githubusercontent.com/28509720/114449436-b7777a80-9ba2-11eb-9d8d-378d15c4d768.png)

**Comment by 0sm0s1z** [comment]
Merged and updated to the production site.
